name: Build, Push, and Deploy to ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  # ==================================================
  # BUILD AND PUSH DOCKER IMAGE
  # ==================================================
  build:
    runs-on: ubuntu-latest

    outputs: #######
      image: ${{ steps.login-ecr.outputs.registry }}/${{ vars.ECR_REPOSITORY }}:${{ github.sha }}

    steps:

      # ----------------------------------------------
      # CHECKOUT CODE
      # ----------------------------------------------
      - name: Checkout Code
        uses: actions/checkout@v4

      # ----------------------------------------------
      # CONFIGURE AWS CREDENTIALS
      # ----------------------------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      # ----------------------------------------------
      # LOGIN TO AMAZON ECR
      # ----------------------------------------------
      - name: Login to Amazon ECR
        id: login-ecr 
        uses: aws-actions/amazon-ecr-login@v2

      # ==================================================
      # BUILD
      # ==================================================
      - name: Build Docker Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .

      # ==================================================
      # PUSH
      # ==================================================
      - name: Push Docker Image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG


  # ==================================================
  # DEPLOY TO AMAZON ECS
  # ==================================================
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

      # ----------------------------------------------
      # CHECKOUT CODE
      # ----------------------------------------------
      - name: Checkout Code
        uses: actions/checkout@v4

      # ----------------------------------------------
      # CONFIGURE AWS CREDENTIALS
      # ----------------------------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      # ----------------------------------------------
      # DOWNLOAD CURRENT ECS TASK DEFINITION
      # ----------------------------------------------
      - name: Download Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition nginx-app \                
            --query taskDefinition > task-definition.json

      # ----------------------------------------------
      # UPDATE TASK DEFINITION WITH NEW IMAGE
      # ----------------------------------------------
      - name: Render Amazon ECS Task Definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: nginx #pull name from task definition json
          image: ${{ needs.build.outputs.image }}

      # ==================================================
      # DEPLOY
      # ==================================================
      - name: Deploy Amazon ECS Task Definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: nginx-service  # name of smy service.Pull name from task defintion json
          cluster: nginx-cluster  #name of my cluster. pull name from task definition json
          wait-for-service-stability: true
          force-new-deployment: true   ##############